### ISSUE TITLE
Algengar flóknar skipanir

### ISSUE THREAD

**Issue by ghost** [gaui/git#2]
Sumar skipanir eru flóknar, algengar en þó nógu sjaldgæfar til að ég muni þær ekki.

Það væri gaman að sjá section, git oneliners.

Undo remote commit, alter remote commit message, finn út rett eftir commit að skrá var added sem atti ekki að vera undir git, osfv.

**Comment by gaui** [comment]
Undo remote commit? Ertu þá að tala um revert?

Alter remote commit message? Þetta geriru ekki með shared history. Þetta felur í sér `commit --amend` (sem breytir local committinu) og svo `push --force` sem force'ar að pusha því yfir á remote. Maður á aldrei að force pusha þegar maður er að vinna á shared branchi.

Finna út rétt eftir að skrá var added sem átti ekki að vera undir Git? Ef þú ert ekki búinn að pusha, þá geturu soft/mixed resettað á staðinn og breytt því og committað aftur, og svo pushað.
